### ISSUE TITLE
Feature 1 - User can create an account

### ISSUE THREAD

**Issue by MitchellMaliglig** [MitchellMaliglig/TF2-BCCG#1]
## 💰 Motivation

People want to make an account to use the app.

## 📐 Plan

Create pages for the home, log in, and sign up screens. Additionally, create the backend APIs for user creation / authentication.

## 🖼️ Wireframes

https://www.figma.com/design/zDraZ5MVvAmgIKVyLsUfaQ/Mitchell-Maliglig---Full-Stack-Project?node-id=1-4&node-type=canvas&t=6QBJv9c8BRNXoRTc-0

## ✅ Task List
- [x] create APIs for user creation / authentication
  - [x] user signs up
  - [x] user signs in
  - [x] test APIs
- [x] create user context
- [x] create user creation / authentication front end 
  - [x] create header / home page
  - [x] create login / sign up page
  - [x] test front end
- [x] Review / modify code
