### ISSUE TITLE
Feature 2 - User can view entries

### ISSUE THREAD

**Issue by MitchellMaliglig** [MitchellMaliglig/TF2-BCCG#3]
## 💰 Motivation

People want to see the entries they've made.

## 📐 Plan

Create dummy entry / user data to be used, then the API to get all entries based on user id. Next, write code to list the entries on the entries page.

## 🖼️ Wireframes

https://www.figma.com/design/zDraZ5MVvAmgIKVyLsUfaQ/Mitchell-Maliglig---Full-Stack-Project?node-id=1-4&node-type=canvas&t=6QBJv9c8BRNXoRTc-0

## ✅ Task List
- [x] create dummy data
  - [x] users
  - [x] entries
- [x] write API to get all entries based on current user
- [x] write code to list entries on the entries page
  - [x] list entries based on user id
  - [x] create a card component w/ icons to enhance the visuals
- [x] add copy to clipboard functionality to the paper icon
- [x] Review / modify code
