### ISSUE TITLE
Feature 3 - User can create entries

### ISSUE THREAD

**Issue by MitchellMaliglig** [MitchellMaliglig/TF2-BCCG#5]
## 💰 Motivation

People want to create some entries.

## 📐 Plan

Build the API to handle entry creation, then design a page for entry creation.

## 🖼️ Wireframes

![tf2bccg-gen-cc](https://github.com/user-attachments/assets/a4a9008a-3a8e-4cd2-9291-3868a60b3ba2)

## ✅ Task List
- [x] build API to handle entry creation 
- [x] design a page for entry creation
  - [x] create the form to generate console commands
  - [x] display commands as they are generated
  - [x] allow user to modify commands
  - [x] implement & test save functionality 
- [x] Review / modify code
