### ISSUE TITLE
Feature 4 - User can modify entries 

### ISSUE THREAD

**Issue by MitchellMaliglig** [MitchellMaliglig/TF2-BCCG#7]
## 💰 Motivation

People want to modify their entries.

## 📐 Plan

Create APIs to update, delete, and grab entries based on entry id. Next, update entry page to allow for entry modification.

## 🖼️ Wireframes

https://www.figma.com/design/zDraZ5MVvAmgIKVyLsUfaQ/Mitchell-Maliglig---Full-Stack-Project?node-id=1-4&node-type=canvas&t=6QBJv9c8BRNXoRTc-0

## ✅ Task List
- [x] Create APIs for entry modification based on entry id
  - [x] update an entry
  - [x] delete an entry
  - [x] grab an entry
- [x] Update entry page to allow for entry modification
  - [x] add navigation to the pencil icons and grab the correct entry
  - [x] display correct commands based on selected entry
  - [x] prepopulate title & description based on selected entry
  - [x] modify save button to implement update functionality 
  - [x] add delete button to implement delete functionality
- [x] Review / modify code

**Comment by MitchellMaliglig** [comment]
check later:
- `EntryPage.tsx` 
  - `handleRemoveCommand()`
- `EntryCard.tsx` 
  - `handleCopy()`
